import type { Product, ComboOffer } from '@/types';

// Unsplash photo IDs for fashion
const PHOTO = {
  tee1: 'photo-1618354691373-d851c5c3a990',
  tee2: 'photo-1521572163474-6864f9cf17ab',
  shirt1: 'photo-1598033129183-c4f50c736f10',
  shirt2: 'photo-1602810318383-e386cc2a3ccf',
  hoodie1: 'photo-1556821840-3a63f15732ce',
  hoodie2: 'photo-1509942774463-acf339cf87d5',
  cargo1: 'photo-1624378439575-d8705ad7ae80',
  cargo2: 'photo-1594938298603-c8148c4dae35',
  jeans1: 'photo-1542272604-787c3835535d',
  jeans2: 'photo-1541099649105-f69ad21f3246',
  shorts1: 'photo-1565084888279-aca607ecce0c',
  fragrance1: 'photo-1541643600914-78b084683702',
  acc1: 'photo-1620799140408-edc6dcb6d633',
  model1: 'photo-1539109136881-3be0616acf4b',
  model2: 'photo-1487222477894-8943e31ef7b2',
  model3: 'photo-1515886657613-9f3515b0c78f',
  model4: 'photo-1503341504253-dff4815485f1',
  lifestyle1: 'photo-1445205170230-053b83016050',
  lifestyle2: 'photo-1469334031218-e382a71b716b',
};

function unsplash(id: string, w = 800, h = 1000): string {
  return `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&h=${h}&q=80`;
}

export const MOCK_PRODUCTS: Product[] = [
  // ── Oversized Tees ──────────────────────────────────────
  {
    id: 'ot-001',
    slug: 'obsidian-classic-oversized-tee-black',
    name: 'Classic Oversized Tee',
    brand: 'OBSIDIAN',
    category: 'oversized-tees',
    description: 'The quintessential OBSIDIAN tee. Premium 240gsm cotton, dropped shoulders, boxy cut.',
    price: 999,
    mrp: 1499,
    discount: 33,
    images: [
      { src: unsplash(PHOTO.tee1), alt: 'Obsidian Classic Oversized Tee Black', width: 800, height: 1000 },
      { src: unsplash(PHOTO.model1), alt: 'Model wearing Classic Oversized Tee', width: 800, height: 1000 },
    ],
    hoverImage: { src: unsplash(PHOTO.model1), alt: 'Model wearing tee', width: 800, height: 1000 },
    colors: [
      { name: 'Obsidian Black', hex: '#0A0A0B' },
      { name: 'Bone White', hex: '#FAFAF9' },
      { name: 'Charcoal', hex: '#1C1C1E' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    stock: { XS: 5, S: 10, M: 15, L: 8, XL: 3, XXL: 2 },
    tags: ['oversized', 'cotton', 'classic', 'bestseller'],
    isNew: false,
    isBestseller: true,
    isTrending: true,
    rating: 4.8,
    reviewCount: 312,
    sku: 'OT-001-BLK',
    createdAt: '2024-09-01T00:00:00Z',
  },
  {
    id: 'ot-002',
    slug: 'obsidian-graphic-oversized-tee-vintage',
    name: 'Vintage Graphic Oversized Tee',
    brand: 'OBSIDIAN',
    category: 'oversized-tees',
    description: 'Screen-printed vintage graphic on 220gsm acid-washed cotton.',
    price: 1199,
    mrp: 1799,
    discount: 33,
    images: [
      { src: unsplash(PHOTO.tee2), alt: 'Vintage Graphic Oversized Tee', width: 800, height: 1000 },
      { src: unsplash(PHOTO.model2), alt: 'Model in graphic tee', width: 800, height: 1000 },
    ],
    hoverImage: { src: unsplash(PHOTO.model2), alt: 'Model in graphic tee', width: 800, height: 1000 },
    colors: [
      { name: 'Washed Black', hex: '#2A2A2C' },
      { name: 'Vintage Grey', hex: '#8A8A8E' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: { S: 7, M: 12, L: 9, XL: 4, XXL: 1 },
    tags: ['graphic', 'vintage', 'oversized', 'new'],
    isNew: true,
    isBestseller: false,
    isTrending: true,
    rating: 4.6,
    reviewCount: 89,
    sku: 'OT-002-VGB',
    createdAt: '2024-11-15T00:00:00Z',
  },
  // ── Shirts ──────────────────────────────────────────────
  {
    id: 'sh-001',
    slug: 'obsidian-oversized-linen-shirt-ecru',
    name: 'Oversized Linen Shirt',
    brand: 'OBSIDIAN',
    category: 'shirts',
    description: '100% pure linen. Relaxed silhouette, premium mother-of-pearl buttons.',
    price: 1799,
    mrp: 2499,
    discount: 28,
    images: [
      { src: unsplash(PHOTO.shirt1), alt: 'Oversized Linen Shirt Ecru', width: 800, height: 1000 },
      { src: unsplash(PHOTO.model3), alt: 'Model in linen shirt', width: 800, height: 1000 },
    ],
    hoverImage: { src: unsplash(PHOTO.model3), alt: 'Model in linen shirt', width: 800, height: 1000 },
    colors: [
      { name: 'Ecru', hex: '#F2EFE4' },
      { name: 'Obsidian', hex: '#0A0A0B' },
      { name: 'Sage', hex: '#7C9A78' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: { S: 6, M: 11, L: 7, XL: 5, XXL: 2 },
    tags: ['linen', 'shirt', 'premium', 'bestseller'],
    isNew: false,
    isBestseller: true,
    isTrending: false,
    rating: 4.7,
    reviewCount: 178,
    sku: 'SH-001-ECR',
    createdAt: '2024-08-10T00:00:00Z',
  },
  {
    id: 'sh-002',
    slug: 'obsidian-cuban-collar-shirt-black',
    name: 'Cuban Collar Shirt',
    brand: 'OBSIDIAN',
    category: 'shirts',
    description: 'Viscose-blend Cuban collar with subtle tonal print. Relaxed, resort-ready.',
    price: 1599,
    mrp: 2199,
    discount: 27,
    images: [
      { src: unsplash(PHOTO.shirt2), alt: 'Cuban Collar Shirt Black', width: 800, height: 1000 },
      { src: unsplash(PHOTO.model4), alt: 'Model in Cuban collar shirt', width: 800, height: 1000 },
    ],
    hoverImage: { src: unsplash(PHOTO.model4), alt: 'Model in Cuban collar shirt', width: 800, height: 1000 },
    colors: [
      { name: 'Obsidian Black', hex: '#0A0A0B' },
      { name: 'Champagne', hex: '#C6A15B' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: { S: 4, M: 9, L: 6, XL: 3 },
    tags: ['cuban', 'resort', 'shirt', 'trending'],
    isNew: true,
    isBestseller: false,
    isTrending: true,
    rating: 4.5,
    reviewCount: 56,
    sku: 'SH-002-BLK',
    createdAt: '2024-12-01T00:00:00Z',
  },
  // ── Hoodies ─────────────────────────────────────────────
  {
    id: 'hd-001',
    slug: 'obsidian-premium-hoodie-black',
    name: 'Premium Fleece Hoodie',
    brand: 'OBSIDIAN',
    category: 'hoodies',
    description: '380gsm French terry. Brushed interior, kangaroo pocket, ribbed cuffs.',
    price: 2499,
    mrp: 3499,
    discount: 29,
    images: [
      { src: unsplash(PHOTO.hoodie1), alt: 'Premium Fleece Hoodie Black', width: 800, height: 1000 },
      { src: unsplash(PHOTO.model1), alt: 'Model in premium hoodie', width: 800, height: 1000 },
    ],
    hoverImage: { src: unsplash(PHOTO.model1), alt: 'Model in hoodie', width: 800, height: 1000 },
    colors: [
      { name: 'Obsidian Black', hex: '#0A0A0B' },
      { name: 'Charcoal', hex: '#1C1C1E' },
      { name: 'Bone', hex: '#FAFAF9' },
      { name: 'Champagne', hex: '#C6A15B' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
    stock: { XS: 3, S: 8, M: 14, L: 10, XL: 6, XXL: 4, XXXL: 1 },
    tags: ['hoodie', 'premium', 'fleece', 'bestseller'],
    isNew: false,
    isBestseller: true,
    isTrending: true,
    rating: 4.9,
    reviewCount: 487,
    sku: 'HD-001-BLK',
    createdAt: '2024-07-01T00:00:00Z',
  },
  {
    id: 'hd-002',
    slug: 'obsidian-zip-up-hoodie-charcoal',
    name: 'Zip-Up Hoodie',
    brand: 'OBSIDIAN',
    category: 'hoodies',
    description: 'Full-zip hoodie in 350gsm cotton blend. YKK zipper, dual pockets.',
    price: 2199,
    mrp: 3199,
    discount: 31,
    images: [
      { src: unsplash(PHOTO.hoodie2), alt: 'Zip-Up Hoodie Charcoal', width: 800, height: 1000 },
      { src: unsplash(PHOTO.model2), alt: 'Model in zip hoodie', width: 800, height: 1000 },
    ],
    hoverImage: { src: unsplash(PHOTO.model2), alt: 'Model in zip hoodie', width: 800, height: 1000 },
    colors: [
      { name: 'Charcoal', hex: '#1C1C1E' },
      { name: 'Midnight Blue', hex: '#1A2340' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: { S: 5, M: 10, L: 8, XL: 4, XXL: 2 },
    tags: ['zip-up', 'hoodie', 'new'],
    isNew: true,
    isBestseller: false,
    isTrending: false,
    rating: 4.6,
    reviewCount: 94,
    sku: 'HD-002-CHR',
    createdAt: '2024-11-20T00:00:00Z',
  },
  // ── Cargo Pants ─────────────────────────────────────────
  {
    id: 'cp-001',
    slug: 'obsidian-tactical-cargo-pants-black',
    name: 'Tactical Cargo Pants',
    brand: 'OBSIDIAN',
    category: 'cargo-pants',
    description: 'Relaxed-fit ripstop cargo. Six pockets, adjustable waistband, tapered ankle.',
    price: 2799,
    mrp: 3999,
    discount: 30,
    images: [
      { src: unsplash(PHOTO.cargo1), alt: 'Tactical Cargo Pants Black', width: 800, height: 1000 },
      { src: unsplash(PHOTO.model3), alt: 'Model in cargo pants', width: 800, height: 1000 },
    ],
    hoverImage: { src: unsplash(PHOTO.model3), alt: 'Model in cargo pants', width: 800, height: 1000 },
    colors: [
      { name: 'Obsidian Black', hex: '#0A0A0B' },
      { name: 'Olive', hex: '#4A5240' },
      { name: 'Sand', hex: '#C4B49A' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: { S: 4, M: 8, L: 6, XL: 3, XXL: 2 },
    tags: ['cargo', 'tactical', 'bestseller', 'trending'],
    isNew: false,
    isBestseller: true,
    isTrending: true,
    rating: 4.7,
    reviewCount: 203,
    sku: 'CP-001-BLK',
    createdAt: '2024-08-15T00:00:00Z',
  },
  // ── Jeans ────────────────────────────────────────────────
  {
    id: 'jn-001',
    slug: 'obsidian-slim-straight-jeans-black',
    name: 'Slim Straight Jeans',
    brand: 'OBSIDIAN',
    category: 'jeans',
    description: '12oz selvedge denim. Slim through thigh, straight leg. Sanforized, unwashed.',
    price: 2999,
    mrp: 4499,
    discount: 33,
    images: [
      { src: unsplash(PHOTO.jeans1), alt: 'Slim Straight Jeans Black', width: 800, height: 1000 },
      { src: unsplash(PHOTO.model4), alt: 'Model in slim straight jeans', width: 800, height: 1000 },
    ],
    hoverImage: { src: unsplash(PHOTO.model4), alt: 'Model in jeans', width: 800, height: 1000 },
    colors: [
      { name: 'Raw Black', hex: '#1A1A1C' },
      { name: 'Indigo', hex: '#2A3F6F' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: { S: 3, M: 7, L: 5, XL: 4, XXL: 1 },
    tags: ['jeans', 'denim', 'slim', 'bestseller'],
    isNew: false,
    isBestseller: true,
    isTrending: false,
    rating: 4.6,
    reviewCount: 145,
    sku: 'JN-001-BLK',
    createdAt: '2024-09-10T00:00:00Z',
  },
  // ── Track Pants ──────────────────────────────────────────
  {
    id: 'tp-001',
    slug: 'obsidian-track-pants-black',
    name: 'Signature Track Pants',
    brand: 'OBSIDIAN',
    category: 'track-pants',
    description: 'Technical poly-blend. Side zip pockets, elasticated waist, tapered cut.',
    price: 1899,
    mrp: 2799,
    discount: 32,
    images: [
      { src: unsplash(PHOTO.cargo2), alt: 'Obsidian Track Pants Black', width: 800, height: 1000 },
      { src: unsplash(PHOTO.model1), alt: 'Model in track pants', width: 800, height: 1000 },
    ],
    hoverImage: { src: unsplash(PHOTO.model1), alt: 'Model in track pants', width: 800, height: 1000 },
    colors: [
      { name: 'Obsidian Black', hex: '#0A0A0B' },
      { name: 'Champagne', hex: '#C6A15B' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    stock: { XS: 2, S: 6, M: 11, L: 8, XL: 4, XXL: 2 },
    tags: ['track', 'athleisure', 'new', 'trending'],
    isNew: true,
    isBestseller: false,
    isTrending: true,
    rating: 4.7,
    reviewCount: 128,
    sku: 'TP-001-BLK',
    createdAt: '2024-12-05T00:00:00Z',
  },
  // ── Fragrance ────────────────────────────────────────────
  {
    id: 'fr-001',
    slug: 'obsidian-noir-edp-100ml',
    name: 'OBSIDIAN Noir EDP',
    brand: 'OBSIDIAN',
    category: 'fragrance',
    description: 'Dark & luxurious. Notes of black oud, sandalwood, vetiver, and musk. 100ml.',
    price: 2499,
    mrp: 3499,
    discount: 29,
    images: [
      { src: unsplash(PHOTO.fragrance1), alt: 'OBSIDIAN Noir EDP 100ml', width: 800, height: 1000 },
    ],
    hoverImage: { src: unsplash(PHOTO.fragrance1), alt: 'Obsidian Noir bottle', width: 800, height: 1000 },
    colors: [{ name: 'Single', hex: '#C6A15B' }],
    sizes: ['M'], // One size
    stock: { M: 20 },
    tags: ['fragrance', 'oud', 'luxury', 'bestseller'],
    isNew: false,
    isBestseller: true,
    isTrending: false,
    rating: 4.9,
    reviewCount: 267,
    sku: 'FR-001-100',
    createdAt: '2024-06-01T00:00:00Z',
  },
];

export const BESTSELLERS = MOCK_PRODUCTS.filter((p) => p.isBestseller);
export const NEW_ARRIVALS = MOCK_PRODUCTS.filter((p) => p.isNew);
export const TRENDING = MOCK_PRODUCTS.filter((p) => p.isTrending);

export const COMBO_OFFERS: ComboOffer[] = [
  {
    id: 'combo-1',
    title: 'Buy 2 Save More',
    description: 'Pick any 2 tees or shirts and save 20% extra',
    type: 'buy-2',
    discount: 20,
    badge: 'SAVE 20%',
    products: MOCK_PRODUCTS.filter((p) =>
      ['oversized-tees', 'shirts'].includes(p.category),
    ).slice(0, 4),
  },
  {
    id: 'combo-2',
    title: 'Buy 3, Free Shipping',
    description: 'Mix & match any 3 items for guaranteed free delivery',
    type: 'buy-3',
    discount: 0,
    badge: 'FREE SHIP',
    products: MOCK_PRODUCTS.slice(0, 4),
  },
  {
    id: 'combo-3',
    title: 'Mix & Match',
    description: 'Pair a hoodie with cargo pants and save ₹500',
    type: 'mix-match',
    discount: 500,
    badge: 'SAVE ₹500',
    products: MOCK_PRODUCTS.filter((p) =>
      ['hoodies', 'cargo-pants'].includes(p.category),
    ).slice(0, 4),
  },
];

export const CATEGORIES = [
  { id: 'oversized-tees', label: 'Oversized Tees', image: unsplash(PHOTO.tee1, 600, 750), href: '/categories/oversized-tees', count: 42 },
  { id: 'shirts', label: 'Shirts', image: unsplash(PHOTO.shirt1, 600, 750), href: '/categories/shirts', count: 28 },
  { id: 'hoodies', label: 'Hoodies', image: unsplash(PHOTO.hoodie1, 600, 750), href: '/categories/hoodies', count: 34 },
  { id: 'track-pants', label: 'Track Pants', image: unsplash(PHOTO.cargo2, 600, 750), href: '/categories/track-pants', count: 18 },
  { id: 'cargo-pants', label: 'Cargo Pants', image: unsplash(PHOTO.cargo1, 600, 750), href: '/categories/cargo-pants', count: 22 },
  { id: 'jeans', label: 'Jeans', image: unsplash(PHOTO.jeans1, 600, 750), href: '/categories/jeans', count: 16 },
  { id: 'shorts', label: 'Shorts', image: unsplash(PHOTO.shorts1, 600, 750), href: '/categories/shorts', count: 20 },
  { id: 'fragrance', label: 'Fragrance', image: unsplash(PHOTO.fragrance1, 600, 750), href: '/categories/fragrance', count: 8 },
  { id: 'accessories', label: 'Accessories', image: unsplash(PHOTO.acc1, 600, 750), href: '/categories/accessories', count: 35 },
];

export const HERO_IMAGES = [
  { src: unsplash(PHOTO.lifestyle1, 1920, 1080), alt: 'OBSIDIAN lifestyle — dark editorial fashion' },
  { src: unsplash(PHOTO.lifestyle2, 1920, 1080), alt: 'OBSIDIAN — premium menswear collection' },
  { src: unsplash(PHOTO.model3, 1920, 1080), alt: 'OBSIDIAN — new arrivals campaign' },
];

export const UGC_GALLERY = [
  unsplash(PHOTO.model1, 500, 500),
  unsplash(PHOTO.model2, 500, 500),
  unsplash(PHOTO.model3, 500, 500),
  unsplash(PHOTO.model4, 500, 500),
  unsplash(PHOTO.tee1, 500, 500),
  unsplash(PHOTO.hoodie1, 500, 500),
  unsplash(PHOTO.cargo1, 500, 500),
  unsplash(PHOTO.jeans1, 500, 500),
  unsplash(PHOTO.lifestyle1, 500, 500),
];

export const CUSTOMER_REVIEWS = [
  {
    id: 'r1', author: 'Arjun Sharma', avatar: unsplash(PHOTO.model4, 100, 100),
    rating: 5, content: 'Absolutely love the quality. The Obsidian hoodie is worth every rupee — super soft and the fit is perfect. Will definitely be ordering more.',
    date: '2024-12-15', verified: true,
  },
  {
    id: 'r2', author: 'Priya Mehta', avatar: unsplash(PHOTO.model3, 100, 100),
    rating: 5, content: 'Finally a brand that gets premium fashion right in India. The linen shirt is chef\'s kiss. Packaging was stunning too!',
    date: '2024-11-28', verified: true,
  },
  {
    id: 'r3', author: 'Rahul Nair', avatar: unsplash(PHOTO.model1, 100, 100),
    rating: 4, content: 'Great quality, fast delivery. The cargo pants are exactly as described. Only wish they had more colour options.',
    date: '2024-12-02', verified: true,
  },
  {
    id: 'r4', author: 'Ananya Singh', avatar: unsplash(PHOTO.model2, 100, 100),
    rating: 5, content: 'Been buying from OBSIDIAN for 6 months now. Consistent quality, great customer support, and the pieces always look exactly like the photos.',
    date: '2024-12-10', verified: true,
  },
];

export const NAV_ITEMS = [
  {
    label: 'New Arrivals',
    href: '/collections/new-arrivals',
    children: [],
  },
  {
    label: 'Shop',
    href: '/shop',
    children: [
      { label: 'Oversized Tees', href: '/categories/oversized-tees', image: unsplash(PHOTO.tee1, 300, 400) },
      { label: 'Shirts', href: '/categories/shirts', image: unsplash(PHOTO.shirt1, 300, 400) },
      { label: 'Hoodies', href: '/categories/hoodies', image: unsplash(PHOTO.hoodie1, 300, 400) },
      { label: 'Track Pants', href: '/categories/track-pants', image: unsplash(PHOTO.cargo2, 300, 400) },
      { label: 'Cargo Pants', href: '/categories/cargo-pants', image: unsplash(PHOTO.cargo1, 300, 400) },
      { label: 'Jeans', href: '/categories/jeans', image: unsplash(PHOTO.jeans1, 300, 400) },
      { label: 'Shorts', href: '/categories/shorts', image: unsplash(PHOTO.shorts1, 300, 400) },
      { label: 'Fragrance', href: '/categories/fragrance', image: unsplash(PHOTO.fragrance1, 300, 400) },
      { label: 'Accessories', href: '/categories/accessories', image: unsplash(PHOTO.acc1, 300, 400) },
    ],
  },
  {
    label: 'Bestsellers',
    href: '/collections/bestsellers',
    children: [],
  },
  {
    label: 'Combos',
    href: '/combos',
    children: [],
  },
  {
    label: 'About',
    href: '/about',
    children: [],
  },
];

export const ANNOUNCEMENT_MESSAGES = [
  { id: 'a1', text: '🚚 Free Shipping on orders above ₹999', link: '/shop', linkText: 'Shop Now' },
  { id: 'a2', text: '💳 Cash on Delivery Available Across India' },
  { id: 'a3', text: '↩️ Easy 7-Day Returns — No Questions Asked' },
  { id: 'a4', text: '⚡ Limited Time: Extra 20% off on combo packs', link: '/combos', linkText: 'Grab the Deal' },
  { id: 'a5', text: '⭐ Rated 4.8/5 by 10,000+ happy customers' },
];
